### ISSUE TITLE
^C^C during Process Whole Buffer causes problems

### ISSUE THREAD

**Issue by jonleivent** [psteckler/ProofGeneral#19]
Processing script wavl.v from [https://github.com/jonleivent/mindless-coding-phase2](url)
Using PG version dd04741, Coq 8.6 version 3e794be, Emacs 24.4.1

Do a Process Whole Buffer, wait a short time, then ^C^C.  Different conditions occur, due to the non-determinancy.  Some are:
1. ^C^C stops Coqtop subprocesses, no message (although have Emacs message function defun'ed to be nil, as per your instructions).  Whole buffer remains highlighted blue, meaning under locked region.  Subsequent use of "Check" button retracts to some point, but then "Next" does nothing.
2. ^C^C causes pop-up message saying something about Coq subprocesses (sorry, I didn't note the complete message before clicking OK by accident), locked region retracted to some point, but subsequent attempts at Undo cause pop-up saying "Can't undo, incomplete response from Coq".  Next does nothing.
3. ^C^C just stops, no message again, but buffer not all blue (it didn't get that far).  Click "Check" button, and it retracts to some point, Next works, but then after some more commands, part of the buffer gets a bright yellow highlight - what does that mean?

**Comment by psteckler** [comment]
Note that I have recently changed the debug message mechanism, so you should not defun `message' to be a no-op any longer. That will allow other message to come through.

**Comment by psteckler** [comment]
I've committed some code that makes interrupts work better. Sometimes the coqtop process exits, but that's apparently an issue with coqtop. When that happens, the buffer is retracted, and you can start over without restarting Emacs. 

When coqtop remains alive, you should be able to continue processing. Depending on a race condition between Coq and PG, when processing the immediate next line, control might revert back to the current line, and you'll need to process it again.

If you see a bright yellow highlight, it means Coq thinks the line just processed has an error. That probably happened because PG and Coq got out of synch, so a valid line was submitted out of sequence. I hope my changes fix that situation.

The "incomplete-response-on-Undo" message is probably valid. When processing wavl.v, if I process past the proof of Fixpoint delete, and then undo to before the Qed, I'll get that message. That's because Coq is still processing the consequence of that Undo. In that situation, PG does not know what the state of Coq's STM is until the Undo finishes. It should finish eventually, and then more Undos are possible. Just now, it took a few minutes for that Undo to finish on my laptop. Within the proof of `delete', Undos are nearly instantaneous.

Let me know if you notice improvements in the interrupt handling.

**Comment by psteckler** [comment]
I'm closing this issue, because many things have changed since it was filed, including interrupt handling and the way the buffer is colored, so that the symptoms reported aren't so useful now.

If there are still problems with interrupts, please open a new issue.
