### ISSUE TITLE
*response* buffer is too big

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#29]
In PG-xml:
![image](https://cloud.githubusercontent.com/assets/396076/18687342/840ef702-7f34-11e6-8c65-db4a46bd6932.png)
In vanilla PG:
![image](https://cloud.githubusercontent.com/assets/396076/18687370/a1a6812c-7f34-11e6-938d-d9df6e3dd402.png)

**Comment by psteckler** [comment]
This behavior seems to be because `coq-optimise-resp-windows' is not in the fork. The fallback behavior is to make the \*goals\* and \*response\* buffers the same size.

I'll see if I can add that code back in.

**Comment by psteckler** [comment]
After writing something to the response buffer, PG now calls the response window optimization routine (if the option is enabled), which dynamically adjusts its size. 

The code was not being called, because in vanilla PG, it was tied to a hook associated with the proof shell way of doing output.

See if this fixes the issue (it may also fix #31).

**Comment by psteckler** [comment]
Can I close this issue?

**Comment by psteckler** [comment]
Closing ...
