### ISSUE TITLE
No face setting for errored regions

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#30]
I have this in my `~/.emacs`:
```elisp
(defun coq-fix-annoying-colors ()
  (when (not (display-graphic-p))
    (setq overlay-arrow-string "")
    (set-face-attribute 'proof-locked-face nil
                        :background "darkblue" :underline nil)
    (set-face-attribute 'proof-incomplete-face nil
                        :background "red")
    (set-face-attribute 'proof-processing-face nil
                        :background "lightblue")))

(add-hook 'coq-mode-hook #'coq-fix-annoying-colors t)
```
Yet I don't see any red on errors:
![image](https://cloud.githubusercontent.com/assets/396076/18687568/867c3ce2-7f35-11e6-9156-aa12205ae06d.png)

**Comment by psteckler** [comment]
I think you want to set proof-error-face, rather than proof-incomplete-face, for errors. Currently, that face is used both for words like "Error" in the response buffer, and for errors in the script, unless they're on the last line processed, as when single-stepping.

Errors on the last line processed use proof-warning-face (yellowish), in a span that disappears after some seconds.

The face proof-incomplete-face is for Qeds before the validation done via the gears button.

**Comment by JasonGross** [comment]
Thanks!
