### ISSUE TITLE
Toplevel errors not reported when jumping

### ISSUE THREAD

**Issue by maximedenes** [psteckler/ProofGeneral#4]
If I jump after an error, nothing is printed. For example, in a file containing:

Check (true : False).

If I jump after that command, Coq does not complain! Going step by step, it does, though.

**Comment by psteckler** [comment]
There are several things involved here. It's a corner case, where the error occurs in the first line, so the state id in the fail value is the initial state id, so there's no span with that id. And some other things. Should have a fix today.

**Comment by psteckler** [comment]
I think I've fixed this.

The error triggers two things, a feedback with an error message, and when PG sends a Status call, there's a failure value. The feedback colors the offending span in red, while the failure value triggers an Edit_at to the state when the erroneous statement was sent.

PG was not actually sending the Edit_at, because there's no span corresponding to the initial state id, and the code didn't work in that corner case.

We also have to deal with colored-red error span in a special way. In general, an Edit_at triggers a retract in PG, which removes spans below the point of retraction -- except we want to keep around this red span in the case that a retraction was triggered by an error. So there's some code now to deal with that (although there's a potential race condition, maybe I can fix that later).

If you edit the erroneous line, the red span now is removed via a modification hook.

**Comment by psteckler** [comment]
I found another bug related to this example. If you single-step through the file, the error is found, and control returns to the top of the file. If you try to single-step again, there's a failure, because the state id has not been reset to the starting state id.

Again, it's a corner case, where there's no span associated with the starting state id.

I've just committed a fix.

**Comment by psteckler** [comment]
As far as I know, this coloring issue is now fixed.
