### ISSUE TITLE
Looping tactic colored too early

### ISSUE THREAD

**Issue by maximedenes** [psteckler/ProofGeneral#6]
On the script:

Goal nat.
repeat (generalize 0).

If I ctrl+c ctrl+n twice, the repeat gets colored as if it was processed, whereas it is in fact looping.

**Comment by psteckler** [comment]
I think I know what's going on here.

The code in PG that processes transactions with coqtop is receiving the feedback messages that would color the text, but they're not reported back to the main PG code, because the value end-tag is never sent. The code explicitly waits until the value end-tag is received before sending a new call, which behavior we want to keep.

I can have the code look for other end tags, like those for feedbacks and messages, but those cannot be allowed to trigger sending a queued item.

**Comment by psteckler** [comment]
I've committed a fix; please try it.

I'm a bit worried about this one, because the eager processing of feedbacks and messages might have side-effects.

**Comment by gares** [comment]
I looked at the log, it is almost correct but not quite.
typically you do 2 calls: Goals;Status
here Goals fails (User Interrupt) but you still do Status before taking care of the error and running Edit_at to the safe id given back by Goals.

You should interrupt the "Goals;Status" sequence as soon as one fails (in CoqIDE you also do Evars I think, but I could not see it there).

The problem with your current way of doing is that one has to interrupt Coq twice, since both Goals and Status loop (i.e. they both ask Coq to evaluate the last sentence).

**Comment by gares** [comment]
BTW, the coloring is now fine, even if in PG I was typically getting a light-red color for yet-to-be-checked sentences, while here I see a light-flashy-azure.  To me the semantics of the old and the new color is the same (even if I guess the coloring routines are different), so I suggest you use the old color, since users are used to it.

**Comment by psteckler** [comment]
Added code to flush queue on fail value, so that Status is not called after the failed Goals. Closing this issue (we can deal with color schemes later :-)).
