### ISSUE TITLE
Some display problems, race conditions

### ISSUE THREAD

**Issue by ejgallego** [psteckler/ProofGeneral#73]
I use alternative keybindings for undo/redo in PG so I can perform these operations quite fast. In the new branch, I see some behavior that looks like a race condition:

1. When doing `proof-assert-next-command-interactive` in quick succession, the mark seems lost. Video: https://x80.org/tmp/pg-race-1.mp4
2. When doing `proof-undo-last-successful-command`, sometimes it moves the cursor but not the mark. Video: https://x80.org/tmp/pg-race-2.mp4

**Comment by ejgallego** [comment]
Relevant setup code to ease the reproduction of these problems:
```elisp
(eval-after-load 'proof-script
    '(progn
       (define-key proof-mode-map "\M-n" 'proof-assert-next-command-interactive)
       (define-key proof-mode-map "\M-p" 'proof-undo-last-successful-command)))
```

**Comment by ejgallego** [comment]
For the second case, `*coq-log*` shows that no `EditAt` is generated.

**Comment by ejgallego** [comment]
For the first issue, the only thing I can think of is that some feedback messages are delayed causing the coloring not to be updated.

**Comment by psteckler** [comment]
I'm not following the first issue (despite watching the video). You're marking a region, then doing Alt-n in quick succession?

I see that if I set the mark at the beginning of the file, Alt-n extends the region. You're losing the region at some point?

**Comment by ejgallego** [comment]
The first issue is the lack of "pending" mark, see where the cursor is, but however the region is not marked.

**Comment by ejgallego** [comment]
The only input I do in the video is a few `Alt-n`, note also the "artifact" that happens in the middle.

**Comment by psteckler** [comment]
Where is the mark set, at the file beginning?

**Comment by psteckler** [comment]
Sorry for not following. What should the behavior be, and how does what I see differ from that?

**Comment by ejgallego** [comment]
I will upload a video with the old PG later, thanks

**Comment by ejgallego** [comment]
Ok two new videos:

- https://x80.org/tmp/old-pg.mp4
- https://x80.org/tmp/new-pg.mp4

note the lack of "purple" coloring in the new version. By the way, printing with new version is way slower, I dunno if it is a Coq problem, a Richpp problem (certainly a very unoptimized format) or an emacs problem, but jut that makes PG feel considerably more sluggish.

**Comment by psteckler** [comment]
On Wed, Jan 25, 2017 at 1:21 PM, Emilio Jesús Gallego Arias
<notifications@github.com> wrote:
> I dunno if it is a Coq problem, a Richpp problem (certainly a very unoptimized format) or an emacs problem, but jut that makes PG feel considerably more sluggish.

Well, I think some degree of slowdown is expected. The vanilla version
of PG does some regexp matching, but the XML version has to parse XML
into an S-expression and then do pattern-matching against that. On top
of that, there's the unescaping of all the XML, and re-escaping of
everything that's displayed, that is, the richpp terms.

**Comment by psteckler** [comment]
On Wed, Jan 25, 2017 at 1:21 PM, Emilio Jesús Gallego Arias
<notifications@github.com> wrote:
> Ok two new videos:
>
> https://x80.org/tmp/old-pg.mp4
> https://x80.org/tmp/new-pg.mp4
>
> note the lack of "purple" coloring in the new version.

OK, this difference might be due to the new way that PG organizes its
spans. It's a bit hard to tell from the videos, because I think you've
changed the faces (colors) for the spans.

Old PG: there are two primary spans, the queue-span, for statements
the PG has examined and put into its internal queue, and the locked
span, for statements that PG has sent to Coq. Those are pink and blue,
respectively. IIRC, the locked span always begins at the buffer start,
and the queue-span starts just where the locked span ends.

New PG: there are three primary spans, the two old ones plus a sent
span, for statements that have been sent to Coq. The locked span now
simply indicates whether a statement has been moved from the internal
queue to the transaction queue. The color for both the queue span and
the locked span are now both pink, so the user can't really
distinguish them. (I think there is some difference as to which is
read-only, but that's not important for your example.) The sent span
is blue. The reason for these colors is that it roughly corresponds to
the user experience in the old PG.

What happens if you don't use custom faces? Is there still a difference?

**Comment by ejgallego** [comment]
I was not using custom faces, however I did some other cleanups and I can't reproduce issue 1 now. Ummm, I dunno if PG is interacting badly with other modes, or maybe with `desktop-mode`.... I will research more.

Issue 2 still seems present thou, doing a few random forward-backward commands there are some times where back only moves the cursor but doesn't retract the proof. Also, by doing forward very fast (basically letting `Alt-n` down) in a proof with error, I got to make PG do funny things, like falling into an infinite loop.

**Comment by psteckler** [comment]
Hmmm, the colors in the video look much different than what I'm used to.

OK, we'll keep this open. If there's a way to reproduce a specific error, I'll look into it.

**Comment by ejgallego** [comment]
Have you tried to use the keybindings I suggested? They enable much faster "back and forward" testing of PG, then if you do `Alt-n/p` quite fast you may see what I mean for the second issue.

**Comment by psteckler** [comment]
Yes, I enabled those keybindings, although I only tried the `Alt-n` one. I'll try out the second one.

**Comment by psteckler** [comment]
I tried out the `Alt-p` keybinding. If I lean on that key chord, I do see frequent "Coq still working" messages. Other than that, I don't see anything unusual.

**Comment by ejgallego** [comment]
Yeah, dunno what more we can do remotely. If I go back and forward a few times the second issue appears.

**Comment by psteckler** [comment]
Let's see, are you doing one step forward, then one step back, or multiple steps?

**Comment by ejgallego** [comment]
A (seemingly) consistent strategy to reproduce it in my computer using Coq 8.6.

1. load this file http://pastebin.com/d8Ck0mWk
2. maintain <kbd>Alt-n</kdb> pressed until the error happens.
3. now, do "back-forward-back-forward"

**Comment by psteckler** [comment]
The error is in `Lemma cats1`, for argument `addn1`, yes?

So going back and forward asserts and undoes the preceding Goal, the big conjunction of `True`'s, right?

That works smoothly here (of course).

**Comment by ejgallego** [comment]
This is what happens here: note the second retract doesn't work, the next add resets the buffer.

**Comment by psteckler** [comment]
Can you paste the contents the *coq-log* buffer when that happens?

**Comment by ejgallego** [comment]
Done, thanks http://pastebin.com/z3wSRhGm

**Comment by psteckler** [comment]
Thanks. 

I think what's happening is that after that last fail-value, which should provoke an EditAt to state id 19, PG is not finding a span for that state id, so it retracts the buffer to state id 1.

I think the span may be getting deleted by the code that creates the previous EditAt to state id 19. That's a funny call, because 19 is the current state id.

**Comment by psteckler** [comment]
I created a branch `no-retract-curr-state`. If there's an attempt to retract to the current state, a message appears in the minibuffer (and \*Messages\* buffer) about that, and no EditAt is sent.

See if this change fixes the problem. It's kind of a guess, since I can't reproduce the problem here. But worth a try.

**Comment by ejgallego** [comment]
I hope I can try tomorrow, thanks (bear with me if no). Is there some additional low-level debugging that should be enabled?

**Comment by psteckler** [comment]
If it doesn't work, we can try to see where the relevant span is deleted. I think that's in the find-and-forget procedure in coq.el, but not certain.

**Comment by psteckler** [comment]
Do you still see the full retraction of the buffer?

**Comment by ejgallego** [comment]
With my config yes, with the minimal one, no.

**Comment by psteckler** [comment]
Probably the config is changing some timings.

Maybe I can add some debug messages.

**Comment by ejgallego** [comment]
Ok, so I nailed it down to `(setq-default column-number-mode 't)` !!! In an empty config (save for PG-xml), if I enable this variable, I start to get the `NOT RETRACTING` msg...

Can you reproduce?

**Comment by psteckler** [comment]
Yes, I see that.

In the server-protocol branch, I just observed a complete retraction after
evaluating that expression.

**Comment by psteckler** [comment]
The exact sequence to trigger a complete retraction:

- eval `(setq-default column-number-mode 't)`
- `Alt-n` until the error in `cats1` is triggered
- `Alt-n` again
- `Alt-p` 
- `Alt-n`

**Comment by ejgallego** [comment]
Really bizarre...

**Comment by ejgallego** [comment]
That is exactly what I see.

**Comment by psteckler** [comment]
I think that last Undo is leaving PG in an inconsistent state. Investigating ...

**Comment by psteckler** [comment]
For an Undo, PG finds a span at the point. Then it searches backward, starting just before the the start of the found span, for a span with a state id.

Apparently, setting `column-number-mode` causes the span with a state id to start a couple of characters before the found span, instead of flush with it.

Rather than trying to work out why that change occurs, I can adjust the algorithm so that it rejects the state id span if it overlaps the found span, and keeps searching.

Subtle, indeed!

**Comment by psteckler** [comment]
I've committed a fix to the `server-protocol` branch, see if it works for you.

**Comment by ejgallego** [comment]
Umm, that looks very weird indeed; why would `column-number-mode` have any effect on the span location? Is that an emacs bug?

This may be the symptom of something else, I am not sure if I am comfortable with the fix.

**Comment by ejgallego** [comment]
Do you have some simple span-setting `elisp` that behaves differently wrt `column-number-mode` ?

I've looked in the emacs sources, and indeed it is hard to explain what is going on.

**Comment by psteckler** [comment]
I don't see anything in PG that mentions `column-number-mode`. 

I just checked, the spans created appear to be the same, whether columns are displayed or not.

What's probably different is the span that's found on retract, and used to cue the backwards search. When columns are displayed, the found span is not a state-id span, but one of the coloring spans. My guess is that it's the current state-id span when columns are not displayed. 

The found span comes from old PG code, not Coq-specific, that looks for a span with the `'type` property. There may be several such spans at a given point, and the one chosen is arbitrary (just the head of the list of such spans). It may be that Emacs returns different span list when column display is enabled, for whatever reason.

The fix itself should be otherwise harmless, as far as I can see.

**Comment by ejgallego** [comment]
Thanks for the explanation, whatever you have done, issue 2 is fixed!!

However, I am still seeing the lack of mark (issue 1); will investigate more and report back.

**Comment by ejgallego** [comment]
I confirm issue 1 does not happen with a minimal configuration.

**Comment by ejgallego** [comment]
Umm, can't reproduce the issue now... closing for now then.
