### ISSUE TITLE
Does not detect incomplete proofs

### ISSUE THREAD

**Issue by RalfJung** [psteckler/ProofGeneral#81]
Consider the following file:
```
Lemma foo : False.
Proof.
idtac.
Qed.
```
If I open this file with CoqIDE and tell it to "Go to end", it shwos a red background for the `Qed` and hovering says "attempt to close incomplete proof".

If I do the same with PG, it shows everything in different shades of blue, and no error. I have to say "Proof General - Check" to get an error.

Notice that I did *not* explicitly ask CoqIDE to "fully check the document". That is not necessary. I think PG should also catch such incomplete proofs when processing the file, without the user having to explicitly ask for any additional checks.

**Comment by psteckler** [comment]
With Coq 8.5pl2, which I have as my current version for other reasons, I do see the error with PG/xml. The Qed is highlighted in red, and the error message appears in the `*Response*` buffer.

I'll check with 8.6 soon.

**Comment by psteckler** [comment]
It seems the behavior depends on whether async processing is enabled. If off, it looks like the error is marked in the buffer, otherwise not. This is true for 8.5 and 8.6.

I'll investigate more.

**Comment by psteckler** [comment]
Independently of the async setting, Coq sends a feedback which PG/xml reports in the `*response*` buffer, showing the error.

If async is disabled, Coq sends back a failure-value, which causes PG/xml to highlight the error in the buffer, and request a backtrack to the state before the offending script line. If async is enabled, the failure-value is not sent, allowing processing to continue.

A fix here could be to mark the error using the feedback information, instead of the failure-value information. When async is off, we get the feedback with a non-existent state id, which is OK, because the failure-value will allow us to mark the error. When async is on, the state id is valid, and we use that to do the marking.

**Comment by psteckler** [comment]
I've committed a fix, please try it!

If the `Qed.' for the incomplete proof is the last statement processed, it's highlighted in yellow, as for all such errors. Otherwise, it's highlighted in red.

**Comment by psteckler** [comment]
Has this issue been fixed adequately?

**Comment by RalfJung** [comment]
The `Qed` behavior is like it is in CoqIDE now, thanks :)

Something else broke though, I am still trying to find a small example demonstrating that...

**Comment by RalfJung** [comment]
Hm, that other issue turned out to be entirely non reproducible. I am actually seeing weird flukes like that quite frequently (frequently enough that I cannot yet use this branch for productive work), but when I try to do the exact same thing again, they don't happen again. I often don't even know exactly what it is that I did. Is there any way to report such issues in a way that is helpful for you?

**Comment by psteckler** [comment]
Well, unless I can reproduce the error, it's hard to know what's gone wrong.

All I can suggest is, always enable logging, and when an error occurs, file an issue and when relevant, include the log.

I do appreciate the issues you've filed so far and the clear descriptions of the bugs!
