### ISSUE TITLE
Syntax error are marked in red, while other errors come back to white

### ISSUE THREAD

**Issue by jhjourdan** [psteckler/ProofGeneral#98]
```
Definition d : bool := 1.
```

The error is shown in *response*, but the command stays in white.

```
1 = 2.
```

The syntax error is shown in *response*, and the command becomes red. This is inconsistent.

**Comment by psteckler** [comment]
The difference occurred because Coq responds differently to these two errors. Coq accepts the first statement, but then issues a fail-value when PG/xml sends a Goal message. PG/xml didn't have a span associated with that message, so it didn't know where to highlight.

When PG/xml sent the second statement, and Coq immediately sends a fail-value, so PG/xml associated the error with the span representing the statement.

I've pushed a fix, where PG/xml updates the span for the traffic queue only when that span is non-nil. So when the first statement is sent, that span is updated. When the fail-value is received for the subsequent Goal request, which has no actual associated span, the same span is used.

It's a bit of a hack, but it's compensating for the way Coq is handling the first statement. The fail-value has locations that correspond to that statement, but nothing in the fail-value tells you which statement is involved.

See if the fix is acceptable.

**Comment by jhjourdan** [comment]
Seems to work, thanks !
